-- MySQL Script generated by MySQL Workbench
-- Wed Jan  6 10:07:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema angelshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema angelshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `angelshop` DEFAULT CHARACTER SET utf8 ;
USE `angelshop` ;

-- -----------------------------------------------------
-- Table `angelshop`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `street` VARCHAR(50) NOT NULL,
  `streetNo` INT NOT NULL,
  `zip` CHAR(5) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `angelshop`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_account_address_idx` (`address` ASC),
  CONSTRAINT `fk_account_address`
    FOREIGN KEY (`address`)
    REFERENCES `angelshop`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);




-- -----------------------------------------------------
-- Table `angelshop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `angelshop`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `angelshop`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `angelshop`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `angelshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(100) NULL,
  `price` DECIMAL(7,2) NOT NULL,
  `discount` INT NOT NULL DEFAULT 0,
  `amount` INT NOT NULL DEFAULT '1',
  `size` VARCHAR(50) NULL,
  `weight` VARCHAR(50) NULL,
  `color` INT NOT NULL,
  `material` INT NOT NULL,
  `manufacturer` INT NOT NULL,
  `category` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_products_category1_idx` (`category` ASC),
  INDEX `fk_products_color1_idx` (`color` ASC),
  INDEX `fk_products_material1_idx` (`material` ASC),
  INDEX `fk_products_manufacturer1_idx` (`manufacturer` ASC),
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category`)
    REFERENCES `angelshop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_color1`
    FOREIGN KEY (`color`)
    REFERENCES `angelshop`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_material1`
    FOREIGN KEY (`material`)
    REFERENCES `angelshop`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_manufacturer1`
    FOREIGN KEY (`manufacturer`)
    REFERENCES `angelshop`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `angelshop`.`payMethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`payMethod` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `angelshop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `payMethod` INT NOT NULL,
  `account` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_payMethod1_idx` (`payMethod` ASC),
  INDEX `fk_order_account1_idx` (`account` ASC),
  CONSTRAINT `fk_order_payMethod1`
    FOREIGN KEY (`payMethod`)
    REFERENCES `angelshop`.`payMethod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_account1`
    FOREIGN KEY (`account`)
    REFERENCES `angelshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `angelshop`.`orderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `angelshop`.`orderItems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `order` INT NOT NULL,
  `products` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderItems_order1_idx` (`order` ASC),
  INDEX `fk_orderItems_products1_idx` (`products` ASC),
  CONSTRAINT `fk_orderItems_order1`
    FOREIGN KEY (`order`)
    REFERENCES `angelshop`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderItems_products1`
    FOREIGN KEY (`products`)
    REFERENCES `angelshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
